### SET SAMPLING CONFIGURATION FOR RUNS
burnInSamples: 500
chains: 25
plotCorner: true
plotTrace: true
progressBar: false
runDir: /gscratch/astro/moeyensj/atm/atm_data/paper1/runs/sigma10
samples: 3000
scaling: 0.01
threads: 25
